# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/kgiusti/go-fdo-client
%global goipath         github.com/kgiusti/go-fdo-client
%global commit          9376c854f808b2617d261cdee79017a548ae3ca0
%global gomodulesmode   GO111MODULE=on

%gometa -L -f

%global common_description %{expand:
go-fdo-client is a tool for performing onboarding of IoT devices}

%global godocs          README.md

Name:           go-fdo-client
Version:        0

## TODO: autorelease not working for C9?
## Release:        %%autorelease -p
Release:        0%{?dist}
Summary:        IoT FIDO device onboarding tool

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description} %{expand:
}

### %%gopkg

# Generated by running `go-mods-to-bundled-provides.py | sort` in source repo
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/blob)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/cbor)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/cbor/cdn)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/cose)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/custom)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/fsim)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/http)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/http/internal/httputil)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/internal/nistkdf)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/kex)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/plugin)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/protocol)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/serviceinfo)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/fido-device-onboard/go-fdo/tpm)) = 0.0.0-20250601145551.git2778c77d4779
Provides: bundled(golang(github.com/google/go-tpm/legacy/tpm2)) = 0.9.5
Provides: bundled(golang(github.com/google/go-tpm/tpm2)) = 0.9.5
Provides: bundled(golang(github.com/google/go-tpm/tpm2/transport)) = 0.9.5
Provides: bundled(golang(github.com/google/go-tpm/tpm2/transport/linuxtpm)) = 0.9.5
Provides: bundled(golang(github.com/google/go-tpm/tpmutil)) = 0.9.5
Provides: bundled(golang(github.com/google/go-tpm/tpmutil/tbs)) = 0.9.5
Provides: bundled(golang(github.com/spf13/cobra)) = 1.9.1
Provides: bundled(golang(hermannm.dev/devlog)) = 0.5.0
# End of generated provides

%gopkg

%prep
### %%goprep -A -k
%goprep -k
%autopatch -p1

%if %{without bootstrap}
%build
export GOFLAGS="-mod=vendor"
echo "Building go-fdo-client..."
## %%gobuild -o %%{gobuilddir}/bin/go-fdo-client %%{goipath}
%gobuild -o %{gobuilddir}/bin/go-fdo-client ./main.go
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%doc README.md
%{_bindir}/go-fdo-client
%endif

%gopkgfiles

%changelog
%autochangelog
