# Generated by go2rpm 1.16.0
%bcond check 1

# scancode has a lot of dependencies, so it can be disabled for a faster build
# or when its deps are unavailable.
%if %{defined rhel} || "%{_arch}" == "i386"
%global go_vendor_license_check_disable 1
%endif

# https://github.com/fido-device-onboard/go-fdo-client
%global goipath         github.com/fido-device-onboard/go-fdo-client
%global commit          837c3aca86a3d44344f7edd5703cf13adfc22fc2

%gometa -L -f

%global common_description %{expand:
go-fdo-client is the device-side implementation of FIDO Device Onboard
specification in Go. It provides an FDO client that interacts with
FDO manufacturer, rendezvous, and owner servers to perform device onboarding.
}

Name:           go-fdo-client
Version:        0
Release:        %autorelease -p
Summary:        None

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description %{common_description}

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/go-fdo-client %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gocheck
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md
%{_bindir}/go-fdo-client


%changelog
%autochangelog
